Repository gardener/gardenlogin, pull requests merged in 2024-02, with the labels that each got.

#78 Support `shoots/viewerkubeconfig`
  README.md
  cmd/get_client_certificate.go
  cmd/get_client_certificate_test.go
  internal/certificatecache/store/store_test.go
  internal/certificatecache/types.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l, area/ipcei

#83 [hotfix-v0.5] Log `shoots/viewerkubeconfig` fallback with V-level `4`
  cmd/get_client_certificate.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#82 [master] Log `shoots/viewerkubeconfig` fallback with V-level `4`
  cmd/get_client_certificate.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#88 Make repo compliant
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/xl, reviewed/lgtm, needs/ok-to-test
