Repository gardener/gardenlogin, pull requests merged in 2025-08, with the labels that each got.

#232 Declare release assets
  .github/workflows/release.yaml
Labels: needs/review, needs/second-opinion, reviewed/ok-to-test, needs/rebase, size/s

#239 Update minor dependencies
  go.mod
  go.sum
Labels: needs/review, needs/second-opinion, reviewed/lgtm, size/l

#237 Use golangci-lint `wsl_v5`
  .golangci.yaml
Labels: reviewed/lgtm, size/xs

#236 Add CI Build badge
  README.md
Labels: reviewed/lgtm, size/xs

#241 disable cache for release builds
  .github/workflows/build.yaml
Labels: reviewed/lgtm, size/xs

#248 Do not bump `LATEST` version file for bump commit
  .github/workflows/release.yaml
Labels: needs/review, size/xs

#255 Add workflow to prepare hotfix branch
  .github/workflows/prepare-hotfix-branch.yaml
Labels: reviewed/lgtm, size/xs

#257 GithubAction: Reuse cherry-pick action
  .github/workflows/cherry-pick.yaml
Labels: reviewed/lgtm, size/xs

#260 ci: replace additional flags with explicit vars
  .ci/build
  .ci/verify
  .github/workflows/build.yaml
  hack/build-darwin-amd64.sh
  hack/build-darwin-arm64.sh
  hack/build-linux-amd64.sh
  hack/build-linux-arm64.sh
  hack/build-windows-amd64.sh
  hack/build.sh
  hack/golangci-lint.sh
  hack/test-integration.sh
Labels: reviewed/lgtm, size/s
